### ISSUE TITLE
Customize database

### ISSUE THREAD

**Issue by wjj666** [ivlachos/agamemnon#4]
Hi,

I want to calculate the abundance with reference genomes by agamemnon for metagenomic samples. In our reference database, each fasta file has a GTDB taxonomy without the NCBI Accession Number. Could you please give me some sugesstion for this problem?

Thank you.

**Comment by gskoufos** [comment]
Hi,

At the moment AGAMEMNON only works with NCBI taxonomy but we are working on adding built-in support for more taxonomy schemes (including GTDB).

Nevertheless, you can use AGAMEMNON's alignment and quantification engines to get abundances for whatever microbial sequences/genomes you want; the only thing that will not (seamlessly) work is the taxonomic calculations step.

Next, you can use the files comprising the raw abundance estimations (i.e., quantification results) and write your own script to aggregate read counts from different microbial sequences (e.g., scaffolds, contigs) under the same strains, aggregate read counts from strains belonging to the same species and so on. 

I will let you know when we officially add support for GTDB but in the meantime, feel free to ask any questions related to the development of your own GTDB-taxonomy script using AGAMEMNON's raw quantification files!

Best,
Giorgos

**Comment by gskoufos** [comment]
Hi,

For now, I'm closing this issue but feel free to re-open if you have additional questions!

Cheers!
